version: "3.8"

services:
  mongo:
    image: mongo:6.0
    ports: 
      - 27017:27017
    restart: unless-stopped
    networks:
      - cscmu-mongodb
    volumes:
      - ./data-volume:/data/db
      - ./initdb:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 7B2NBV5kcvr61OIB
      MONGO_INITDB_DATABASE: cscmu_mongo
  
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - cscmu-mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 7B2NBV5kcvr61OIB
      ME_CONFIG_MONGODB_URL: mongodb://root:7B2NBV5kcvr61OIB@mongo:27017/

  jupyter-sql:
    image: jupyter
    build: ./jupyter
    ports:
      - 8888:8888
    networks:
      - cscmu-mongodb
    volumes:
      - ./exercise_notebooks:/var/notebooks

volumes:
  data-volume: 

networks:
  cscmu-mongodb:
    # for development
    driver: bridge
    # for production
    #driver: overlay
