version: '3.1'

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 8080:80
    depends_on:
      - "db"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306:3306
      PMA_USER: root
      PMA_PASSWORD: secret

  jupyter:
    image: jupyter-sql
    build: ./jupyter-sql
    container_name: jupyter
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
    volumes:
      - ./ipynb:/home/jovyan/work

volumes:
  data-volume:
  sql:
  jupyter-ipynb:
