version: '3.1'

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./default-sql-db:/docker-entrypoint-initdb.d:ro
      - ./data-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 8080:80
    depends_on:
      - "db"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306:3306
      PMA_USER: root
      PMA_PASSWORD: secret

  jupyter-sql:
    image: jupyter-sql
    build: ./jupyter-sql
    ports:
      - 8888:8888
    expose:
      - "8888"
    volumes:
      - ./sql-notebooks:/var/notebooks

volumes:
  data-volume:
